---
title: "Project Part 3: Statistical Analysis Plan"
output: 
  rmdformats::robobook:
    css: "homework.css"
    highlight: pygments
link-citations: yes
---

**Due:** Wednesday, April 15, 11:59pm on Canvas

# Overview

So far, you have used exploratory data analysis and linear regression with a single predictor to answer your research questions. The next step will be to add more variables to your model(s), to answer more in-depth questions.

When working with lots of variables, it is easy to fall down a rabbit hole exploring different models. To make sure you choose reasonable models that help you address your research questions, it is often helpful to plan out some steps of your analysis in advance. You do not have to stick to these steps completely, but having an idea of what you will do ahead of time is useful.

In this part of the project, you will come up with a plan for answering some research questions, and submit your plan to receive feedback. You do not have to actually do the analysis yet!

# Data

The [College Scorecard](https://collegescorecard.ed.gov/), compiled by the US Department of Education, is meant to be a tool for college applicants to compare different institutions. In this project, you will work with data from the scorecard to advise a high school senior on choosing a college. (We will use data that are several years old, so may be slightly out of date, but we will hope that the same general trends are still true today).

## Variables

The dataset provided for this project contains the following columns:

* `INSTNM`: school name
* `STABBR`: state in which the school is located
* `CONTROL`: whether the school is public or private
* `SATVRMID`: midpoint of SAT critical reading scores of students attending the school
* `SATMTMID`: midpoint of SAT math scores
* `SATWRMID`: midpoint of SAT writing scores
* `ACTCMMID`: midpoint of the ACT cumulative scores
* `ACTENMID`: midpoint of ACT English scores
* `ACTMTMID`: midpoint of ACT math scores
* `ACTWRMID`: midpoint of ACT writing scores
* `UGDS`: number of undergraduate students at the school
* `NPT4`: average cost to attend the school
* `PCTFLOAN`: fraction of undergraduates receiving a federal student loan
* `MD_EARN_WNE_P10`: median salary of students 10 years after graduation
* `GRAD_DEBT_MDN_SUPP`: median debt of graduated students
* `RPY_3YR_RT_SUPP`: proportion of students who are actively repaying their loans 3 years after graduation
* `RPY_3YR_70`: whether the proportion of students actively repaying their loans 3 years after graduation is > 70% (1 = yes, 0 = no)

## Downloading the data

The data for this project is stored in a CSV file, and can be imported into R with the `read_csv` function in the `readr` package. The following code imports the data and saves it as a data frame called `scorecard`:

```r
scorecard <- read_csv("https://sta112-s26.github.io/projects/scorecard.csv")
```

## Research questions

For this project, suppose you have been approached by a high school senior applying to college. They are looking through the college scorecard data, and they have some questions for you about the value of different schools.

1. Do students who graduate from more expensive schools earn more money after graduation, after accounting for student debt, school type (public or private), and the test scores of enrolled students?

2. Is the relationship between school cost and graduate earnings the same for public and private schools, after accounting for student debt and the test scores of enrolled students?


# Your task in Part 3

Your task in part 3 is to create a **Statistical Analysis Plan** (SAP) that describes how you will go about answering the two research questions described above. **You will not do any analysis for this part of the project!** Once you have completed the SAP, the final part of the project (Part 4) will be to carry out the analysis you described in your plan.

Your analysis plan should be approximately 1--2 pages, and must address the following questions. Note that some of the initial questions you will have already addressed in previous parts of the project; since a complete SAP discusses these questions, I still want you to discuss them in this part.

1. What is/are the research question(s) or objectives?
2. What are the variables that will be measured in the study? For each variable, what will the
data look like?
    * This includes the response variable, the explanatory variable of interest, and any other
variables to include in your analysis
3. What is the study design, and why is the study set up this way?
    * You aren’t designing the data collection, so here I really want you to describe
the following:
        * What is the source of the data, and how were they collected?
        * What is the size of the data, and what does a row in the data represent?
        * Are there any missing observations?
        * Is there any dependence (e.g. groups) between observations?
4. How will data and any patterns/results be summarized? (i.e., how you will do exploratory
data analysis). (Note: you will be considering some additional explanatory variables, so you may need to do more EDA than what you did in Part 1!)
5. What will be examined statistically? Link directly back to the research questions.
    * Which models will you fit?
    * How will you assess the suitability of these models? (diagnostics, etc.)
    * How will you use the models to address the research question(s)? (hypothesis tests,
confidence intervals, etc.)
    * What software will you use?
6. What alternative strategies should be considered, and when? (i.e., what will you do if as-
sumptions are violated? How would you modify the model or statistical analysis?)
7. What are the statistical results that will be presented? (refer back to 4 and 5)

See the following article (particularly Table 1) for more guidance on crafting a statistical analysis
plan:

Cressman, K. A., & Sharp, J. L. (2022). [Crafting statistical analysis plans: A cross-discipline
approach](https://onlinelibrary.wiley.com/doi/abs/10.1002/sta4.528). *Stat*, 11(1), e528.

# Appearance and style

This part of the project does not need to be down in Quarto, since you won't be doing any analysis -- just describing your plan. You can submit your work as an html file, Word document, pdf, etc.


Your SAP will answer each of the questions described above, and it is ok to divide your SAP by question. However, your answers to each question *must* be written in full sentences and paragraphs, with sufficient detail to describe how you will carry out your analysis. Bulleted lists and sentence fragments are not acceptable, and will receive lower scores.

# Use of AI and other outside resources, and citing sources

The point of this part of the project is for you to practice coming up with an analysis plan, using your statistical knowledge. Therefore, you are **prohibited** from using AI to generate the big ideas in your plan. For example, you may *not* give AI prompts such as "What models should I fit to answer these research questions?", "What variables should I include in my model?", "What diagnostics should I perform?", etc.

You *may* use AI (or other resources such as a google search) for smaller, more focused questions, such as: "How do I check the constant variance assumption using a residual plot?" (Though, I would still prefer you avoid AI here -- at this point in the course, you should really know the answers to these kinds of questions).

Any use of AI or other outside sources must explicitly be cited. If you use AI, you must provide the specific AI tool used, and give all prompts you asked the AI.

Inappropriate use of AI, or failure to appropriately cite outside resources, will be treated as plagiarism and may result in a grade of 0 and further reporting to the Honors and Ethics Council. 






