---
title: Project Part 3 -- Statistical Analysis Plan
output:
  xaringan::moon_reader:
    css: "lab-slides.css"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---


### Project so far

.large[

* `MED_EARNINGS`: median earnings for graduates from each university
* `CONTROL`: whether the school is public or private
* `SATVRMID`: midpoint of SAT critical reading scores of students attending the school
* `SATMTMID`: midpoint of SAT math scores
* `SATWRMID`: midpoint of SAT writing scores
* `ACTCMMID`: midpoint of the ACT cumulative scores
* `ACTENMID`: midpoint of ACT English scores
* `ACTMTMID`: midpoint of ACT math scores
* `+` others...

.question[
Research goal: want to investigate relationship between different school characteristics and graduate earnings.
]
]

---

### Project Parts 3 and 4

.large[
Suppose a high school senior is looking through the college scorecard data, and they have some questions for you about the value of different schools.

* Do students who graduate from more expensive schools earn more money after graduation, after accounting for student debt, school type (public or private), and the test scores of enrolled students?
* Is the relationship between school cost and graduate earnings the same for public and private schools, after accounting for student debt and the test scores of enrolled students?

**Part 3:** Create a Statistical Analysis Plan, describing how you will analyze the data to address these questions. Due: April 15.

**Part 4:** Carry out your SAP, and present your results in a full written report. Due: April 29 (tentative).
]

---

### Statistical Analysis Plan (SAP)

.large[
A **statistical analysis plan** (SAP) describes:

* the research questions we are trying to answer
* the data we will use to answer the research questions
* how we will use statistical methods (models, diagnostics, hypothesis tests, etc.)
* how we will present our results

**Why?**

* having a plan ahead of time helps organize our work
* research questions should inform analysis and methods (not the other way around)
* helps determine which data we need to collect
* make sure we're doing something reasonable before we do a ton of work!
]

---

### Statistical Analysis Plan (SAP)

.large[
* What is/are the research question(s) or objectives?
* What are the variables that will be measured in the study? For each variable, what will the
data look like?
* What is the study design, and why is the study set up this way?
* How will data and any patterns/results be summarized? (i.e., how you will do exploratory
data analysis).
* What will be examined statistically? Link directly back to the research questions.
* What alternative strategies should be considered, and when?
* What are the statistical results that will be presented?
]

---

### Today

.large[
Today, we will focus on a few of these questions in class:

* What are the variables that will be measured in the study?
* How will data and any patterns/results be summarized? (i.e., how you will do exploratory
data analysis).
* What will be examined statistically?
    * Which models will you fit?
    * How will you assess the suitability of these models? (diagnostics, etc.)
    * How will you use the models to address the research question(s)? (hypothesis tests,
confidence intervals, etc.)
    * What software will you use?
* What alternative strategies should be considered, and when? (i.e., what will you do if assumptions are violated? How would you modify the model or statistical analysis?)

]

---

### Variables

.large[
* Do students who graduate from more expensive schools earn more money after graduation, after accounting for student debt, school type (public or private), and the test scores of enrolled students?
* Is the relationship between school cost and graduate earnings the same for public and private schools, after accounting for student debt and the test scores of enrolled students?

.question[
What variables should we consider to investigate these research questions?
]
]

---

### EDA

.large[
* Do students who graduate from more expensive schools earn more money after graduation, after accounting for student debt, school type (public or private), and the test scores of enrolled students?
* Is the relationship between school cost and graduate earnings the same for public and private schools, after accounting for student debt and the test scores of enrolled students?

.question[
What EDA would you do?
]
]

---

### Statistical methods

.large[
* Do students who graduate from more expensive schools earn more money after graduation, after accounting for student debt, school type (public or private), and the test scores of enrolled students?
* Is the relationship between school cost and graduate earnings the same for public and private schools, after accounting for student debt and the test scores of enrolled students?

.question[
Which models will you fit?
]
]

---

### Statistical methods

.large[
* Do students who graduate from more expensive schools earn more money after graduation, after accounting for student debt, school type (public or private), and the test scores of enrolled students?
* Is the relationship between school cost and graduate earnings the same for public and private schools, after accounting for student debt and the test scores of enrolled students?

.question[
How will you assess the suitability of these models? (diagnostics, etc.)
]
]

---

### Statistical methods

.large[
* Do students who graduate from more expensive schools earn more money after graduation, after accounting for student debt, school type (public or private), and the test scores of enrolled students?
* Is the relationship between school cost and graduate earnings the same for public and private schools, after accounting for student debt and the test scores of enrolled students?

.question[
How will you use the models to address the research question(s)? (hypothesis tests,
confidence intervals, etc.)
]
]

---

### Statistical methods

.large[
* Do students who graduate from more expensive schools earn more money after graduation, after accounting for student debt, school type (public or private), and the test scores of enrolled students?
* Is the relationship between school cost and graduate earnings the same for public and private schools, after accounting for student debt and the test scores of enrolled students?

.question[
What alternative strategies should be considered, and when? (i.e., what will you do if assumptions are violated? How would you modify the model or statistical analysis?)
]
]



