---
title: "Activity: NBA fan attendance"
format: pdf
editor: source
---

\vspace{-1.5cm}

**Group members:**

\vspace{1.5cm}

**Instructions:** Work with a neighbor on the following activity. The icebreaker questions are for us to get to know each other. For the data analysis questions, you'll need to read the linked article on NBA fan attendance. 

I will collect the handout at the end of class, and it will be part of your class participation grade. You will be graded only on effort -- it is ok if you don't finish all the questions, or get them all correct.

In this activity, we'll get to know each other, and you'll answer some questions about data analysis on NBA games. Conducting a data analysis, and communicating your results, are core learning goals for this course. This activity allows you to think about what qualities a good data analysis should have. 


## Icebreaker questions

1. What are you studying at Wake? (This can be your declared major, intended major, or some of the classes you're taking)

\vspace{3cm}

2. What TV show have you been watching lately?

\vspace{3cm}

## The impact of fans on NBA games

In the 2020--2021 National Basketball Association (NBA) season, fan attendance at some games was limited due to pandemic restrictions. Some players believe that they performed differently depending on the number of fans present. So, how much does fan attendance impact basketball games? This article from FiveThirtyEight attempts to answer that question, by analyzing data from 2020--2021 games:

[https://tinyurl.com/nba-fans](https://tinyurl.com/nba-fans)

Read the article and answer the questions:

3. What specific question were the researchers trying to answer?

\vspace{3cm}

4. To answer their research question, the authors gathered data on NBA games. Where did the data come from? Were there any issues with the data?

\vspace{3cm}

5. What statistics and data science tools did the researchers use to come to their conclusions?

\vspace{3cm}

6. What did the researchers conclude about their research question?

\vspace{3cm}

7. Do you agree with their conclusion? Why or why not? Would you do anything differently?

\vspace{3cm}

8. Suppose you wanted to check that the researchers did their analysis correctly. What information would you need to reproduce their results? Is that information available?
