---
title: "Class activity: linear regression"
format: pdf
editor: source
---

\vspace{-2.5cm}

**Group members:**

**Instructions:** Work with a neighbor on the following activity. I will collect the handout at the end of class, and it will be part of your class participation grade. You will be graded only on effort -- it is ok if you don't finish all the questions, or get them all correct.

## Sparrow data

In this activity, you will practice using and interpreting a fitted regression line. We will work with data on 116 sparrows, which were observed on Kent Island, New Brunswick. For each sparrow, we have information including:

* *Weight*: the weight of the sparrow (in grams)
* *WingLength*: the sparrow's wing length (in mm)

This data is included in the `Stat2Data` package (the R package for our class textbook).


## Questions

```{r, echo=F, message=F, warning=F, fig.align='center', fig.width=5, fig.height=3.5}
library(Stat2Data)
library(tidyverse)
data("Sparrows")

Sparrows %>%
  ggplot(aes(x = Weight,
             y = WingLength)) +
  geom_point(size=2) +
  labs(x = "Weight (g)",
       y = "Wing length (mm)",
       title = "Wing length vs. weight for Kent Island sparrows") +
  theme_bw() 
```

1. Based on the plot, is linear regression an appropriate choice for modeling the relationship between weight and wing length?

\vspace{3cm}

We now fit a linear regression, with weight as the explanatory variable and wing length as the response. The equation of the fitted model is

$\widehat{\text{wing length}} = 8.755 + 1.313 \ \text{weight}$

2. What is our estimated intercept, $\widehat{\beta}_0$?

\vspace{1cm}

3. What is our estimated slope, $\widehat{\beta}_1$?

\vspace{1cm}

4. What is the estimated wing length for a sparrow which weighs 15g?

\vspace{2cm}

5. What is the estimated wing length for a sparrow which weights 16g?

\vspace{2cm}

6. Compare your answers to exercises 5 and 6 -- how much does the predicted wing length change when we increase weight by 1g?